CREATE TABLE [dbo].[Trainings] (
    [ID]                              INT NOT NULL IDENTITY,
    [Customer_ID]                     TEXT     NOT NULL,
    [SLOT_date]                       DATETIME NOT NULL,
    [SLOT_ID]                         TEXT     NOT NULL,
    [FFS_type]                        TEXT     NOT NULL,
    [Training_type]                   TEXT     NOT NULL,
    [SLOT_reference]                  TEXT     NOT NULL,
    [SLOT_duration]                   TIME (7) NOT NULL,
    [Training_details]                TEXT     NOT NULL,
    [Instructor]                      TEXT     NOT NULL,
    [Trainee_1]                       TEXT     NOT NULL,
    [Trainee_2]                       TEXT     NOT NULL,
    [Additional_crew_member]          TEXT     NOT NULL,
    [Instructor_position]             TEXT     NOT NULL,
    [Trainee_1_position]              TEXT     NOT NULL,
    [Trainee_2_position]              TEXT     NOT NULL,
    [Additional_crew_member_position] TEXT     NOT NULL,
    [Date_and_time_of_arrival]        DATETIME NOT NULL,
    [Date_and_time_training_begin]    DATETIME NOT NULL,
    [Date_and_time_training_finished] DATETIME NOT NULL,
    [Date_and_time_of_departure]      DATETIME NOT NULL,
    [Data_entered_by]                 TEXT     NOT NULL,
    [Training_duration]               TIME (7) NOT NULL,
    [Problem_report]                  TEXT     NOT NULL,
    [Support_engineer]                TEXT     NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);